//! Differential tests: the Rust cfgfile shims vs the original cfgfile.c
//! compiled as c_ref_*. Both sides read the same config files through the
//! same stub filesystem; since Phase 7 M2 each side's Cvar_Set reaches its
//! real registry (c_ref cvar.c vs the Rust port), so the tested cvars are
//! registered into both registries with a change callback feeding the shared
//! capture log, and the exact change sequences (names, values, order) are
//! compared.

use core::ffi::{c_char, c_int, CStr};
use quake_ctest::fs as ctfs; // also links the cc-built c_ref_* archive

extern "C" {
    fn c_ref_CFG_OpenConfig(cfg_name: *const c_char) -> c_int;
    fn c_ref_CFG_CloseConfig();
    fn c_ref_CFG_ReadCvars(vars: *mut *const c_char, num_vars: c_int);
    fn c_ref_CFG_ReadCvarOverrides(vars: *mut *const c_char, num_vars: c_int);

    fn ctest_clear_cvar_log();
    fn ctest_cvar_log_len() -> c_int;
    fn ctest_cvar_log_get(i: c_int, which: c_int) -> *const c_char;
    fn ctest_set_args(argc: c_int, argv: *mut *mut c_char);
    fn ctest_register_logged_cvar_pair(name: *const c_char);
    fn ctest_reset_logged_cvars(side: c_int);
}

fn snapshot_cvar_log() -> Vec<(String, String)> {
    // SAFETY: log entries are NUL-terminated C strings owned by the stub
    unsafe {
        let n = ctest_cvar_log_len();
        (0..n)
            .map(|i| {
                (
                    CStr::from_ptr(ctest_cvar_log_get(i, 0))
                        .to_string_lossy()
                        .into_owned(),
                    CStr::from_ptr(ctest_cvar_log_get(i, 1))
                        .to_string_lossy()
                        .into_owned(),
                )
            })
            .collect()
    }
}

#[test]
fn cfgfile_differential() {
    let _guard = ctfs::lock();
    // Phase 2: the stub filesystem is gone — CFG_OpenConfig goes through the
    // real COM_FOpenPrefFile (harness_active redirects it into com_gamedir)
    // and COM_FOpenFile (searchpath walk) of each side, so a searchpath
    // (root = tmp, gamedir "cfggame") is mounted on both and the config
    // files live in the gamedir.
    let root = std::env::temp_dir().join(format!("quake-ctest-cfg-{}", std::process::id()));
    let dir = root.join("cfggame");
    std::fs::create_dir_all(&dir).unwrap();
    for side in ctfs::BOTH {
        ctfs::setup(side, &[&root], 0, c"cfggame");
    }

    let config = concat!(
        "// generated by vkQuake\n",
        "unbindall\n",
        "vid_width \"1920\"\r\n",
        "vid_height\t\"1080\"   \n",
        "seta scr_fov \"110\"\n", // seta prefix: no match at line start
        "vid_fsaa \"4\"20\"\n",   // multiple quotes: value after first
        "vid_refreshrate \"unclosed\n", // no trailing quote: skipped
        "vid_fullscreen \"\"\n",  // empty value
        "vid_width \"640\"\n",    // second occurrence (j counting)
        "trailing garbage\n",
    );

    for name in ["vkQuake.cfg", "other.cfg"] {
        std::fs::write(dir.join(name), config).unwrap();
    }

    let vars: Vec<&CStr> = vec![
        c"vid_width",
        c"vid_height",
        c"vid_fsaa",
        c"vid_fullscreen",
        c"vid_refreshrate",
    ];
    let mut c_vars: Vec<*const c_char> = vars.iter().map(|v| v.as_ptr()).collect();

    // SAFETY: valid NUL-terminated names; registers each name into both
    // registries with the logging change callback (see stubs.c)
    unsafe {
        for v in &vars {
            ctest_register_logged_cvar_pair(v.as_ptr());
        }
    }

    // both config names: the CONFIG_NAME path (COM_FOpenPrefFile) and the
    // searchpath one (COM_FOpenFile)
    for cfg in [c"vkQuake.cfg", c"other.cfg", c"missing.cfg"] {
        // SAFETY: valid NUL-terminated names and vars arrays; the stub log is
        // cleared between the two sides
        unsafe {
            ctest_clear_cvar_log();
            let c_open = c_ref_CFG_OpenConfig(cfg.as_ptr());
            c_ref_CFG_ReadCvars(c_vars.as_mut_ptr(), c_vars.len() as c_int);
            // A second pass exercises FS_rewind state, but it re-sets the
            // same values, which Cvar_SetQuick's no-change early return
            // would swallow -- the pass would log nothing and be invisible
            // here. Drive this side's cvars to a sentinel first so pass 2's
            // sets are real changes. The sentinel writes themselves log,
            // identically on both sides.
            ctest_reset_logged_cvars(0);
            c_ref_CFG_ReadCvars(c_vars.as_mut_ptr(), 2);
            c_ref_CFG_CloseConfig();
            let c_log = snapshot_cvar_log();

            ctest_clear_cvar_log();
            let r_open = quake_rs::cfgfile::CFG_OpenConfig(cfg.as_ptr());
            quake_rs::cfgfile::CFG_ReadCvars(c_vars.as_mut_ptr(), c_vars.len() as c_int);
            ctest_reset_logged_cvars(1);
            quake_rs::cfgfile::CFG_ReadCvars(c_vars.as_mut_ptr(), 2);
            quake_rs::cfgfile::CFG_CloseConfig();
            let r_log = snapshot_cvar_log();

            assert_eq!(c_open, r_open, "open result for {cfg:?}");
            assert_eq!(c_log, r_log, "Cvar_Set sequence for {cfg:?}");
            if cfg != c"missing.cfg" {
                assert!(!c_log.is_empty(), "expected matches for {cfg:?}");
                // pass 2 must actually be observable: a vid_width set has to
                // appear after the sentinel writes
                let sentinel = c_log
                    .iter()
                    .rposition(|(_, v)| v == "\u{1}sentinel")
                    .expect("sentinel writes logged");
                assert!(
                    c_log[sentinel + 1..].iter().any(|(n, _)| n == "vid_width"),
                    "second CFG_ReadCvars pass produced no visible sets for {cfg:?}"
                );
            }
        }
    }

    // command-line overrides
    let args: Vec<std::ffi::CString> = [
        "vkquake",
        "+vid_width",
        "800",
        "+vid_height",
        "-nope",
        "+vid_fsaa",
    ]
    .iter()
    .map(|s| std::ffi::CString::new(*s).unwrap())
    .collect();
    let mut argv: Vec<*mut c_char> = args.iter().map(|a| a.as_ptr() as *mut c_char).collect();
    // SAFETY: argv outlives the calls; same args for both sides
    unsafe {
        ctest_set_args(argv.len() as c_int, argv.as_mut_ptr());

        ctest_clear_cvar_log();
        c_ref_CFG_ReadCvarOverrides(c_vars.as_mut_ptr(), c_vars.len() as c_int);
        let c_log = snapshot_cvar_log();

        ctest_clear_cvar_log();
        quake_rs::cfgfile::CFG_ReadCvarOverrides(c_vars.as_mut_ptr(), c_vars.len() as c_int);
        let r_log = snapshot_cvar_log();

        assert_eq!(c_log, r_log, "override sequences");
        assert_eq!(c_log, vec![("vid_width".to_string(), "800".to_string())]);
    }
}
