/* automatically generated by rust-bindgen 0.72.1 */

// opaque stdio FILE: only ever passed through as a pointer
#[repr(C)]
pub struct FILE {
    _opaque: [u8; 0],
}
// MAX_OSPATH is PATH_MAX (q_types.h), platform-dependent: bindgen would
// have baked the generation host's value into the arrays below.
// The ladder is verified against the engine headers per platform by
// quake-ctest/tests/fs_abi.rs (sizes and field offsets too).
#[cfg(windows)]
pub const MAX_OSPATH: usize = 260;
#[cfg(target_os = "macos")]
pub const MAX_OSPATH: usize = 1024;
#[cfg(all(unix, not(target_os = "macos")))]
pub const MAX_OSPATH: usize = 4096;
#[repr(C)]
pub struct steamgame_s {
    pub appid: ::std::os::raw::c_int,
    pub subdir: *mut ::std::os::raw::c_char,
    pub library: [::std::os::raw::c_char; MAX_OSPATH],
}
pub type steamgame_t = steamgame_s;
#[repr(C)]
pub struct findfile_s {
    pub attribs: fileattribs_t,
    pub name: [::std::os::raw::c_char; MAX_OSPATH],
}
pub type findfile_t = findfile_s;
// com_gamedir is char[MAX_OSPATH]: declared by hand for the same
// platform-dependent-array reason as the structs above.
extern "C" {
    pub static mut com_gamedir: [::std::os::raw::c_char; MAX_OSPATH];
}

pub type byte = ::std::os::raw::c_uchar;
pub type qboolean = bool;
pub type vec_t = f32;
pub type vec3_t = [vec_t; 3usize];
unsafe extern "C" {
    pub fn Mem_Alloc(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn Mem_AllocNonZero(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn Mem_Realloc(
        ptr: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn Mem_Free(ptr: *const ::std::os::raw::c_void);
}
pub type qfilesize_t = ::std::os::raw::c_longlong;
pub type qfileofs_t = ::std::os::raw::c_longlong;
unsafe extern "C" {
    pub fn Sys_GetPrefPath(
        org: *const ::std::os::raw::c_char,
        app: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn Sys_MessageBoxWarning(
        title: *const ::std::os::raw::c_char,
        message: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn Sys_QuitNoShutdown() -> !;
}
unsafe extern "C" {
    pub fn Sys_fseek(
        file: *mut FILE,
        ofs: qfileofs_t,
        origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Sys_ftell(file: *mut FILE) -> qfileofs_t;
}
unsafe extern "C" {
    pub fn Sys_filelength(f: *mut FILE) -> qfilesize_t;
}
unsafe extern "C" {
    pub fn Sys_FileOpenRead(
        path: *const ::std::os::raw::c_char,
        hndl: *mut ::std::os::raw::c_int,
    ) -> qfilesize_t;
}
unsafe extern "C" {
    pub fn Sys_MemFileOpenRead(
        memory: *const byte,
        size: qfilesize_t,
        hndl: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn Sys_DuplicateHandle(handle: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Sys_FileOpenWrite(path: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Sys_FileClose(handle: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn Sys_FileSeek(
        handle: ::std::os::raw::c_int,
        position: qfileofs_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Sys_FileRead(
        handle: ::std::os::raw::c_int,
        dest: *mut ::std::os::raw::c_void,
        count: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Sys_FileWrite(
        handle: ::std::os::raw::c_int,
        data: *const ::std::os::raw::c_void,
        count: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Sys_fopen(
        path: *const ::std::os::raw::c_char,
        mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn Sys_mkdir(path: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn Sys_FileType(path: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
pub const fileattribs_t_FA_DIRECTORY: fileattribs_t = 1;
pub type fileattribs_t = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn Sys_FindFirst(
        dir: *const ::std::os::raw::c_char,
        ext: *const ::std::os::raw::c_char,
    ) -> *mut findfile_t;
}
unsafe extern "C" {
    pub fn Sys_FindNext(find: *mut findfile_t) -> *mut findfile_t;
}
unsafe extern "C" {
    pub fn Sys_FindClose(find: *mut findfile_t);
}
unsafe extern "C" {
    pub fn Sys_GetSteamDir(path: *mut ::std::os::raw::c_char, pathsize: usize) -> qboolean;
}
unsafe extern "C" {
    pub fn Sys_GetGOGQuakeDir(path: *mut ::std::os::raw::c_char, pathsize: usize) -> qboolean;
}
unsafe extern "C" {
    pub fn Sys_GetGOGQuakeEnhancedDir(
        path: *mut ::std::os::raw::c_char,
        pathsize: usize,
    ) -> qboolean;
}
unsafe extern "C" {
    pub fn Sys_GetEGSManifestDir(path: *mut ::std::os::raw::c_char, pathsize: usize) -> qboolean;
}
unsafe extern "C" {
    pub fn Sys_GetEGSLauncherData() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn Sys_GetNightdiveUserDir(
        path: *mut ::std::os::raw::c_char,
        pathsize: usize,
        steamlibrary: *const ::std::os::raw::c_char,
    ) -> qboolean;
}
unsafe extern "C" {
    pub fn Sys_Error(error: *const ::std::os::raw::c_char, ...) -> !;
}
unsafe extern "C" {
    pub fn Sys_Printf(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn Sys_DoubleTime() -> f64;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sizebuf_s {
    pub allowoverflow: qboolean,
    pub overflowed: qboolean,
    pub data: *mut byte,
    pub maxsize: ::std::os::raw::c_int,
    pub cursize: ::std::os::raw::c_int,
}
pub type sizebuf_t = sizebuf_s;
unsafe extern "C" {
    pub static mut msg_readcount: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut msg_badread: qboolean;
}
unsafe extern "C" {
    pub fn q_strtrim(str_: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn COM_Parse(data: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub static mut com_argc: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut com_argv: *mut *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub static mut safemode: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn COM_CheckParm(parm: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn COM_CheckParmNext(
        last: ::std::os::raw::c_int,
        parm: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn COM_FOpenPrefFile(
        filename: *const ::std::os::raw::c_char,
        mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn COM_SkipPath(pathname: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn COM_StripExtension(
        in_: *const ::std::os::raw::c_char,
        out: *mut ::std::os::raw::c_char,
        outsize: usize,
    );
}
unsafe extern "C" {
    pub fn COM_FileBase(
        in_: *const ::std::os::raw::c_char,
        out: *mut ::std::os::raw::c_char,
        outsize: usize,
    );
}
unsafe extern "C" {
    pub fn COM_AddExtension(
        path: *mut ::std::os::raw::c_char,
        extension: *const ::std::os::raw::c_char,
        len: usize,
    );
}
unsafe extern "C" {
    pub fn COM_FileGetExtension(
        in_: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn COM_SeedRand(seed: u64);
}
unsafe extern "C" {
    pub fn COM_Rand() -> i32;
}
unsafe extern "C" {
    pub fn COM_ThreadFileSize() -> qfileofs_t;
}
unsafe extern "C" {
    pub fn COM_ThreadFileFromPak() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn COM_SetThreadFileSize(size: qfilesize_t);
}
unsafe extern "C" {
    pub fn COM_SetThreadFileFromPak(from_pak: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn COM_ThreadToken() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn COM_HostBasedir() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn COM_HostUserdir() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn COM_SetHostUserdir(dir: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn COM_Game_f();
}
unsafe extern "C" {
    pub fn COM_CheckRegistered();
}
unsafe extern "C" {
    pub fn COM_FOpenFile(
        filename: *const ::std::os::raw::c_char,
        file: *mut *mut FILE,
        path_id: *mut ::std::os::raw::c_uint,
    ) -> qfilesize_t;
}
unsafe extern "C" {
    pub fn COM_FileExists(
        filename: *const ::std::os::raw::c_char,
        path_id: *mut ::std::os::raw::c_uint,
    ) -> qboolean;
}
unsafe extern "C" {
    pub fn COM_CloseFile(h: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn COM_LoadFile(
        path: *const ::std::os::raw::c_char,
        path_id: *mut ::std::os::raw::c_uint,
    ) -> *mut byte;
}
unsafe extern "C" {
    pub fn COM_LoadMallocFile_TextMode_OSPath(
        path: *const ::std::os::raw::c_char,
        len_out: *mut ::std::os::raw::c_long,
    ) -> *mut byte;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _fshandle_t {
    pub file: *mut FILE,
    pub pak: qboolean,
    pub start: qfileofs_t,
    pub length: qfilesize_t,
    pub pos: qfileofs_t,
}
pub type fshandle_t = _fshandle_t;
unsafe extern "C" {
    pub fn FS_fread(
        ptr: *mut ::std::os::raw::c_void,
        size: usize,
        nmemb: usize,
        fh: *mut fshandle_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn FS_fseek(
        fh: *mut fshandle_t,
        offset: qfileofs_t,
        whence: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn FS_rewind(fh: *mut fshandle_t);
}
unsafe extern "C" {
    pub fn FS_feof(fh: *mut fshandle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn FS_ferror(fh: *mut fshandle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn FS_fclose(fh: *mut fshandle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn FS_fgets(
        s: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        fh: *mut fshandle_t,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn FS_filelength(fh: *mut fshandle_t) -> qfilesize_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cvar_s {
    pub name: *const ::std::os::raw::c_char,
    pub string: *const ::std::os::raw::c_char,
    pub flags: cvarflags_t,
    pub value: f32,
    pub default_string: *const ::std::os::raw::c_char,
    pub callback: cvarcallback_t,
    pub completion: cvarcompletion_t,
    pub next: *mut cvar_s,
}
unsafe extern "C" {
    pub static mut registered: cvar_s;
}
unsafe extern "C" {
    pub static mut cmdline: cvar_s;
}
pub const cvarflags_t_CVAR_NONE: cvarflags_t = 0;
pub const cvarflags_t_CVAR_ARCHIVE: cvarflags_t = 1;
pub const cvarflags_t_CVAR_NOTIFY: cvarflags_t = 2;
pub const cvarflags_t_CVAR_SERVERINFO: cvarflags_t = 4;
pub const cvarflags_t_CVAR_USERINFO: cvarflags_t = 8;
pub const cvarflags_t_CVAR_CHANGED: cvarflags_t = 16;
pub const cvarflags_t_CVAR_ROM: cvarflags_t = 64;
pub const cvarflags_t_CVAR_LOCKED: cvarflags_t = 256;
pub const cvarflags_t_CVAR_REGISTERED: cvarflags_t = 1024;
pub const cvarflags_t_CVAR_CALLBACK: cvarflags_t = 65536;
pub const cvarflags_t_CVAR_USERDEFINED: cvarflags_t = 131072;
pub const cvarflags_t_CVAR_AUTOCVAR: cvarflags_t = 262144;
pub const cvarflags_t_CVAR_SETA: cvarflags_t = 524288;
pub type cvarflags_t = ::std::os::raw::c_uint;
pub type cvarcallback_t = ::std::option::Option<unsafe extern "C" fn(arg1: *mut cvar_s)>;
pub type cvarcompletion_t = ::std::option::Option<
    unsafe extern "C" fn(var: *mut cvar_s, partial: *const ::std::os::raw::c_char),
>;
pub type cvar_t = cvar_s;
unsafe extern "C" {
    pub fn Cvar_RegisterVariable(variable: *mut cvar_t);
}
unsafe extern "C" {
    pub fn Cvar_SetCallback(var: *mut cvar_t, func: cvarcallback_t);
}
unsafe extern "C" {
    pub fn Cvar_Set(var_name: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn Cvar_SetValue(var_name: *const ::std::os::raw::c_char, value: f32);
}
unsafe extern "C" {
    pub fn Cvar_SetQuick(var: *mut cvar_t, value: *const ::std::os::raw::c_char);
}
pub const quakeflavor_t_QUAKE_FLAVOR_ORIGINAL: quakeflavor_t = 0;
pub const quakeflavor_t_QUAKE_FLAVOR_REMASTERED: quakeflavor_t = 1;
pub type quakeflavor_t = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn Steam_Init(game: *const steamgame_t) -> qboolean;
}
unsafe extern "C" {
    pub fn ChooseQuakeFlavor() -> quakeflavor_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct qmutex_s {
    _unused: [u8; 0],
}
pub type qmutex_t = qmutex_s;
unsafe extern "C" {
    pub fn QMutex_Create() -> *mut qmutex_t;
}
unsafe extern "C" {
    pub fn QMutex_Destroy(mutex: *mut qmutex_t);
}
unsafe extern "C" {
    pub fn QMutex_Lock(mutex: *mut qmutex_t);
}
unsafe extern "C" {
    pub fn QMutex_Unlock(mutex: *mut qmutex_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct portable_samplepair_t {
    pub left: ::std::os::raw::c_int,
    pub right: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sfxcache_t {
    pub length: ::std::os::raw::c_int,
    pub loopstart: ::std::os::raw::c_int,
    pub speed: ::std::os::raw::c_int,
    pub width: ::std::os::raw::c_int,
    pub stereo: ::std::os::raw::c_int,
    pub data: [byte; 1usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sfx_s {
    pub name: [::std::os::raw::c_char; 64usize],
    pub cache: *mut sfxcache_t,
}
pub type sfx_t = sfx_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dma_t {
    pub channels: ::std::os::raw::c_int,
    pub samples: ::std::os::raw::c_int,
    pub submission_chunk: ::std::os::raw::c_int,
    pub samplepos: ::std::os::raw::c_int,
    pub samplebits: ::std::os::raw::c_int,
    pub signed8: ::std::os::raw::c_int,
    pub speed: ::std::os::raw::c_int,
    pub buffer: *mut ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct channel_t {
    pub sfx: *mut sfx_t,
    pub leftvol: ::std::os::raw::c_int,
    pub rightvol: ::std::os::raw::c_int,
    pub end: ::std::os::raw::c_int,
    pub pos: ::std::os::raw::c_int,
    pub looping: ::std::os::raw::c_int,
    pub entnum: ::std::os::raw::c_int,
    pub entchannel: ::std::os::raw::c_int,
    pub origin: vec3_t,
    pub dist_mult: vec_t,
    pub master_vol: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wavinfo_t {
    pub rate: ::std::os::raw::c_int,
    pub width: ::std::os::raw::c_int,
    pub channels: ::std::os::raw::c_int,
    pub loopstart: ::std::os::raw::c_int,
    pub samples: ::std::os::raw::c_int,
    pub dataofs: ::std::os::raw::c_int,
}
unsafe extern "C" {
    pub fn S_PaintChannels(endtime: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn SNDDMA_Init(dma: *mut dma_t) -> qboolean;
}
unsafe extern "C" {
    pub fn SNDDMA_GetDMAPos() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn SNDDMA_Shutdown();
}
unsafe extern "C" {
    pub fn SNDDMA_LockBuffer();
}
unsafe extern "C" {
    pub fn SNDDMA_Submit();
}
unsafe extern "C" {
    pub fn SNDDMA_BlockSound();
}
unsafe extern "C" {
    pub fn SNDDMA_UnblockSound();
}
unsafe extern "C" {
    pub static mut snd_channels: [channel_t; 1024usize];
}
unsafe extern "C" {
    pub static mut snd_mutex: *mut qmutex_t;
}
unsafe extern "C" {
    pub static mut shm: *mut dma_t;
}
unsafe extern "C" {
    pub static mut total_channels: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut soundtime: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut paintedtime: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut s_rawend: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut listener_origin: vec3_t;
}
unsafe extern "C" {
    pub static mut listener_forward: vec3_t;
}
unsafe extern "C" {
    pub static mut listener_right: vec3_t;
}
unsafe extern "C" {
    pub static mut listener_up: vec3_t;
}
unsafe extern "C" {
    pub static mut sndspeed: cvar_t;
}
unsafe extern "C" {
    pub static mut snd_mixspeed: cvar_t;
}
unsafe extern "C" {
    pub static mut snd_filterquality: cvar_t;
}
unsafe extern "C" {
    pub static mut sfxvolume: cvar_t;
}
unsafe extern "C" {
    pub static mut loadas8bit: cvar_t;
}
unsafe extern "C" {
    pub static mut s_rawsamples: [portable_samplepair_t; 8192usize];
}
unsafe extern "C" {
    pub static mut bgmvolume: cvar_t;
}
unsafe extern "C" {
    pub fn S_LoadSound(s: *mut sfx_t) -> *mut sfxcache_t;
}
unsafe extern "C" {
    pub fn GetWavinfo(
        name: *const ::std::os::raw::c_char,
        wav: *mut byte,
        wavlength: ::std::os::raw::c_int,
    ) -> wavinfo_t;
}
unsafe extern "C" {
    pub fn SND_InitScaletable();
}
unsafe extern "C" {
    pub static mut harness_active: qboolean;
}
unsafe extern "C" {
    pub static mut harness_sndhash: qboolean;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct qsocket_s {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub static mut harness_badread_count: ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn Harness_SNDDMA_Init(dma: *mut ::std::os::raw::c_void) -> qboolean;
}
unsafe extern "C" {
    pub fn Harness_SNDDMA_GetDMAPos() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Harness_SNDDMA_Shutdown();
}
unsafe extern "C" {
    pub fn Harness_SndPaint(
        painted: ::std::os::raw::c_int,
        end: ::std::os::raw::c_int,
        paintbuf: *const ::std::os::raw::c_void,
        dmabuf: *const ::std::os::raw::c_uchar,
        dmabytes: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn Con_Printf(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn Con_Warning(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn Con_DPrintf(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn Con_DPrintf2(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn Con_DWarning(fmt: *const ::std::os::raw::c_char, ...);
}
pub type xcommand_t = ::std::option::Option<unsafe extern "C" fn()>;
pub const cmd_source_t_src_client: cmd_source_t = 0;
pub const cmd_source_t_src_command: cmd_source_t = 1;
pub const cmd_source_t_src_server: cmd_source_t = 2;
pub type cmd_source_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cmd_function_s {
    _unused: [u8; 0],
}
pub type cmd_function_t = cmd_function_s;
unsafe extern "C" {
    pub fn Cmd_AddCommand2(
        cmd_name: *const ::std::os::raw::c_char,
        function: xcommand_t,
        srctype: cmd_source_t,
        qcinterceptable: qboolean,
    ) -> *mut cmd_function_t;
}
unsafe extern "C" {
    pub fn Sys_SelectFolder(
        title: *const ::std::os::raw::c_char,
        default_location: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        dstsize: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Image_DecodeSTBMem(
        mem: *const byte,
        len: ::std::os::raw::c_int,
        width: *mut ::std::os::raw::c_int,
        height: *mut ::std::os::raw::c_int,
        failure_reason: *mut *const ::std::os::raw::c_char,
    ) -> *mut byte;
}
unsafe extern "C" {
    pub static mut multiuser: qboolean;
}
unsafe extern "C" {
    pub static mut isDedicated: qboolean;
}
unsafe extern "C" {
    pub static mut developer: cvar_t;
}
unsafe extern "C" {
    pub static mut external_ents: cvar_t;
}
unsafe extern "C" {
    pub static mut snd_waterfx: cvar_t;
}
unsafe extern "C" {
    pub static mut snd_pauselooping: cvar_t;
}
unsafe extern "C" {
    pub static mut precache: cvar_t;
}
unsafe extern "C" {
    pub static mut sn: dma_t;
}
unsafe extern "C" {
    pub static mut host_frametime: f64;
}
unsafe extern "C" {
    pub static mut host_framecount: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Cmd_Argc() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn Cmd_Argv(arg: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn Con_SafePrintf(fmt: *const ::std::os::raw::c_char, ...);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_info_s {
    pub rate: ::std::os::raw::c_int,
    pub bits: ::std::os::raw::c_int,
    pub width: ::std::os::raw::c_int,
    pub channels: ::std::os::raw::c_int,
    pub samples: ::std::os::raw::c_int,
    pub blocksize: ::std::os::raw::c_int,
    pub size: ::std::os::raw::c_int,
    pub dataofs: ::std::os::raw::c_int,
}
pub type snd_info_t = snd_info_s;
pub const stream_status_t_STREAM_NONE: stream_status_t = -1;
pub const stream_status_t_STREAM_INIT: stream_status_t = 0;
pub const stream_status_t_STREAM_PAUSE: stream_status_t = 1;
pub const stream_status_t_STREAM_PLAY: stream_status_t = 2;
pub type stream_status_t = ::std::os::raw::c_int;
pub type snd_codec_t = snd_codec_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_stream_s {
    pub fh: fshandle_t,
    pub pak: qboolean,
    pub name: [::std::os::raw::c_char; 64usize],
    pub info: snd_info_t,
    pub status: stream_status_t,
    pub codec: *mut snd_codec_t,
    pub loop_: qboolean,
    pub priv_: *mut ::std::os::raw::c_void,
}
pub type snd_stream_t = snd_stream_s;
pub type CODEC_INIT = ::std::option::Option<unsafe extern "C" fn() -> qboolean>;
pub type CODEC_SHUTDOWN = ::std::option::Option<unsafe extern "C" fn()>;
pub type CODEC_OPEN =
    ::std::option::Option<unsafe extern "C" fn(stream: *mut snd_stream_t) -> qboolean>;
pub type CODEC_READ = ::std::option::Option<
    unsafe extern "C" fn(
        stream: *mut snd_stream_t,
        bytes: ::std::os::raw::c_int,
        buffer: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type CODEC_REWIND =
    ::std::option::Option<unsafe extern "C" fn(stream: *mut snd_stream_t) -> ::std::os::raw::c_int>;
pub type CODEC_JUMP = ::std::option::Option<
    unsafe extern "C" fn(
        stream: *mut snd_stream_t,
        order: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type CODEC_CLOSE = ::std::option::Option<unsafe extern "C" fn(stream: *mut snd_stream_t)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_codec_s {
    pub type_: ::std::os::raw::c_uint,
    pub initialized: qboolean,
    pub ext: *const ::std::os::raw::c_char,
    pub initialize: CODEC_INIT,
    pub shutdown: CODEC_SHUTDOWN,
    pub codec_open: CODEC_OPEN,
    pub codec_read: CODEC_READ,
    pub codec_rewind: CODEC_REWIND,
    pub codec_jump: CODEC_JUMP,
    pub codec_close: CODEC_CLOSE,
    pub next: *mut snd_codec_t,
}
unsafe extern "C" {
    pub static mut flac_codec: snd_codec_t;
}
unsafe extern "C" {
    pub static mut mp3_codec: snd_codec_t;
}
unsafe extern "C" {
    pub static mut vorbis_codec: snd_codec_t;
}
unsafe extern "C" {
    pub static mut opus_codec: snd_codec_t;
}
unsafe extern "C" {
    pub fn SND_Glue_ClientConnected() -> qboolean;
}
unsafe extern "C" {
    pub fn SND_Glue_ViewEntity() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn SND_Glue_Worldmodel() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn SND_Glue_PointInLeaf(p: *mut f32) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn SND_Glue_PauseLoops() -> qboolean;
}
unsafe extern "C" {
    pub static mut net_message: sizebuf_t;
}
unsafe extern "C" {
    pub static mut net_time: f64;
}
unsafe extern "C" {
    pub static mut net_driverlevel: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn NET_NewQSocket() -> *mut qsocket_s;
}
unsafe extern "C" {
    pub fn NET_FreeQSocket(sock: *mut qsocket_s);
}
unsafe extern "C" {
    pub fn SetNetTime() -> f64;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dgrm_packet_t {
    pub length: ::std::os::raw::c_uint,
    pub sequence: ::std::os::raw::c_uint,
    pub data: [::std::os::raw::c_uchar; 64000usize],
}
unsafe extern "C" {
    pub static mut packetBuffer: dgrm_packet_t;
}
unsafe extern "C" {
    pub static mut packetsSent: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut packetsReSent: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut packetsReceived: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut receivedDuplicateCount: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut shortPacketCount: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut droppedDatagrams: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut messagesReceived: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut unreliableMessagesReceived: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut net_hostport: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut my_ipv4_address: [::std::os::raw::c_char; 64usize];
}
unsafe extern "C" {
    pub static mut my_ipv6_address: [::std::os::raw::c_char; 64usize];
}
unsafe extern "C" {
    pub static mut ipv4Available: qboolean;
}
unsafe extern "C" {
    pub static mut ipv6Available: qboolean;
}
unsafe extern "C" {
    pub static mut net_activeSockets: *mut qsocket_s;
}
unsafe extern "C" {
    pub static mut net_freeSockets: *mut qsocket_s;
}
unsafe extern "C" {
    pub static mut net_activeconnections: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut DEFAULTnet_hostport: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut listening: qboolean;
}
unsafe extern "C" {
    pub static mut hostCacheCount: usize;
}
unsafe extern "C" {
    pub fn NetMain_SVActive() -> qboolean;
}
unsafe extern "C" {
    pub fn NetMain_MaxClients() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn NetMain_MaxClientsLimit() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn NetMain_SetMaxClients(n: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn NetMain_Drivers() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn NetMain_LanDrivers() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn Cbuf_AddText(text: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub static vkquake_pak: [::std::os::raw::c_uchar; 0usize];
}
unsafe extern "C" {
    pub static vkquake_pak_size: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static vkquake_pak_decompressed_size: ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct qcvm_s {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub static mut qcvm: *mut qcvm_s;
}
unsafe extern "C" {
    pub fn PRExec_Glue_PrintStatement(pc: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn PRExec_Glue_SvActive() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRExec_Glue_Strcmp(
        a: *const ::std::os::raw::c_char,
        b: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRExec_Glue_CallBuiltin(index: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceEnabled() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceEnter(fnum: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceLeave();
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceStatement(
        pc: ::std::os::raw::c_int,
        op: ::std::os::raw::c_int,
        a: ::std::os::raw::c_int,
        b: ::std::os::raw::c_int,
        c: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceGlobalWrite(
        ofs: ::std::os::raw::c_int,
        values: *const ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceFieldWrite(
        ofs: ::std::os::raw::c_int,
        values: *const ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceBuiltin(
        ordinal: ::std::os::raw::c_int,
        argc: ::std::os::raw::c_int,
        parms: *const ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn PRExec_Glue_TraceBuiltinReturn(ret: *const ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn PRSave_Glue_FieldAtOfs(
        ofs: ::std::os::raw::c_int,
        type_: *mut ::std::os::raw::c_int,
        field_ofs: *mut ::std::os::raw::c_int,
        s_name: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRParse_Glue_Atof(s: *const ::std::os::raw::c_char) -> f64;
}
unsafe extern "C" {
    pub fn PRParse_Glue_Atoi(s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRParse_Glue_Strtoll(s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_longlong;
}
unsafe extern "C" {
    pub fn PRParse_Glue_Strtoull(s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_ulonglong;
}
unsafe extern "C" {
    pub fn PRParse_Glue_FindFieldOfs(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRParse_Glue_FindFunction(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRParse_Glue_UnlinkEdict(edict_num: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn PRLoad_Glue_MapCreate() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PRLoad_Glue_MapReserve(
        map: *mut ::std::os::raw::c_void,
        capacity: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn PRLoad_Glue_MapInsert(
        map: *mut ::std::os::raw::c_void,
        key: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn PRLoad_Glue_MapDestroy(map: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn PRLoad_Glue_SwitchQCVM(nvm: *mut qcvm_s);
}
unsafe extern "C" {
    pub fn PRLoad_Glue_DeselectQCVM();
}
unsafe extern "C" {
    pub fn PRLoad_Glue_SetPrGlobalStruct(globals: *mut f32);
}
unsafe extern "C" {
    pub fn PRLoad_Glue_SetEmptyEngineString();
}
unsafe extern "C" {
    pub fn PRLoad_Glue_FindFieldOfs(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRLoad_Glue_GlobalFloat(name: *const ::std::os::raw::c_char, out: *mut f32) -> qboolean;
}
unsafe extern "C" {
    pub fn PRLoad_Glue_FindFunction(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PRLoad_Glue_VaComponent(
        name: *const ::std::os::raw::c_char,
        component: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PRLoad_Glue_ShutdownExtensions();
}
unsafe extern "C" {
    pub fn PRLoad_Glue_EnableExtensions(globaldefs: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn PRLoad_Glue_IsServerVM(vm: *mut qcvm_s) -> qboolean;
}
unsafe extern "C" {
    pub fn PRLoad_Glue_SetEffectsMask(mask: ::std::os::raw::c_int);
}
