//! Phase 8 M11 (task plan D8, ADR-015): under the `render` feature the SPIR-V
//! shader blobs and the embedded `vkquake.pak` are produced here by the xtask
//! pipeline instead of Meson's `bintoc`/`mkpak` custom targets, and baked into
//! the staticlib with `include_bytes!` (`src/shaders.rs`, `src/embedded_pak.rs`).
//! Same tools, same flags, same outputs: `scripts/harness/xtask_diff.py` keeps
//! them byte-identical to the C build's.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    if std::env::var_os("CARGO_FEATURE_RENDER").is_none() {
        return;
    }
    let repo = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("quake-capi lives inside the repository")
        .to_path_buf();
    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    println!("cargo:rerun-if-changed={}", repo.join("Shaders").display());
    println!(
        "cargo:rerun-if-changed={}",
        repo.join("Misc").join("vq_pak").display()
    );
    for var in ["QUAKE_GLSLANG", "QUAKE_SPIRV_OPT", "VULKAN_SDK"] {
        println!("cargo:rerun-if-env-changed={var}");
    }

    // meson.build: `-g` and no spirv-opt for every debug* buildtype (the
    // same condition that sets engine-debug), and no spirv-opt when the build
    // machine is macOS. A build script runs on the build machine, so its own
    // target_os is build_machine.system().
    let debug = std::env::var_os("CARGO_FEATURE_ENGINE_DEBUG").is_some();
    let options = xtask::shaders::Options::for_build(debug, cfg!(target_os = "macos"));
    let tools = xtask::shaders::Tools::find(options).unwrap_or_else(|e| panic!("{e}"));
    if !tools
        .spirv_opt_has_canonicalize_ids()
        .unwrap_or_else(|e| panic!("{e}"))
    {
        panic!("spirv-opt does not support --canonicalize-ids, a newer Vulkan SDK is required");
    }

    let shader_dir = out.join("shaders");
    let spvs = xtask::shaders::compile_all(&repo, &shader_dir, options, &tools)
        .unwrap_or_else(|e| panic!("{e}"));
    let mut table = String::from(
        "// generated by build.rs: Shader::name() (the bintoc symbol without _spv) -> SPIR-V blob\n\
         pub(crate) fn spv(name: &str) -> Option<&'static [u8]> {\n    match name {\n",
    );
    for (job, spv) in xtask::shaders::jobs().iter().zip(&spvs) {
        let _ = writeln!(
            table,
            "        {:?} => Some(include_bytes!({:?})),",
            xtask::bintoc::symbol(job.name),
            spv.display().to_string()
        );
    }
    table.push_str("        _ => None,\n    }\n}\n");
    std::fs::write(out.join("shaders_gen.rs"), table).expect("write shaders_gen.rs");

    let vq_pak = repo.join("Misc").join("vq_pak");
    let pak = out.join("vkquake.pak");
    xtask::pak::build(&pak, &vq_pak, &vq_pak.join("vq_pak_contents.txt"), None)
        .unwrap_or_else(|e| panic!("{e}"));
    let pak_bytes = std::fs::read(&pak).expect("read vkquake.pak");
    let deflated = xtask::bintoc::deflate_raw(&pak_bytes);
    let deflated_path = out.join("vkquake.pak.deflate");
    std::fs::write(&deflated_path, &deflated).expect("write vkquake.pak.deflate");
    std::fs::write(
        out.join("embedded_pak_gen.rs"),
        format!(
            "// generated by build.rs: bintoc -c vkquake.pak\n\
             pub(crate) const COMPRESSED: &[u8; {}] = include_bytes!({:?});\n\
             pub(crate) const DECOMPRESSED_SIZE: usize = {};\n",
            deflated.len(),
            deflated_path.display().to_string(),
            pak_bytes.len()
        ),
    )
    .expect("write embedded_pak_gen.rs");
}
