[package]
name = "quake-net"
version = "0.1.0"
description = "MSG_* readers/writers, protocols 15/666/999+PRFL+PEXT, net drivers, demo IO"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
quake-types = { path = "../quake-types" }

[lints]
workspace = true
