#!/bin/bash
# Regenerate the committed bindgen output in rust/quake-c-sys/src/generated.rs.
#
# ADR-011 (as amended in Phase 1): bindings are generated by this script and
# committed, rather than generated at build time, so libclang is not a build
# prerequisite; the rust.yml bindgen-smoke CI job reruns this script and fails
# on any diff, preserving the single-source-of-truth property.
#
# Layout tests are disabled: the committed output must be portable across the
# three CI OSes, and bindgen layout tests hardcode the generation host's type
# sizes. Struct layout drift is covered by the differential test suite in
# rust/quake-ctest and the signature-parity check.
set -euo pipefail
cd "$(dirname "$0")/.."

# FILE is blocklisted and re-declared opaque: bindgen would otherwise expand
# the generation host's libc struct (e.g. Darwin __sFILE), which is not
# portable; the engine only ever passes FILE* through.
bindgen rust/quake-c-sys/bindings_wrapper.h \
    --no-layout-tests \
    --no-doc-comments \
    --blocklist-type 'FILE|__sFILE.*|__sbuf|fpos_t|__darwin_.*|__int64_t|_IO_.*|_iobuf|__off_t|__off64_t' \
    --blocklist-type 'steamgame_s|steamgame_t|findfile_s|findfile_t' \
    --raw-line '// opaque stdio FILE: only ever passed through as a pointer' \
    --raw-line '#[repr(C)]' \
    --raw-line 'pub struct FILE {' \
    --raw-line '    _opaque: [u8; 0],' \
    --raw-line '}' \
    --raw-line '// MAX_OSPATH is PATH_MAX (q_types.h), platform-dependent: bindgen would' \
    --raw-line '// have baked the generation host'"'"'s value into the arrays below.' \
    --raw-line '// The ladder is verified against the engine headers per platform by' \
    --raw-line '// quake-ctest/tests/fs_abi.rs (sizes and field offsets too).' \
    --raw-line '#[cfg(windows)]' \
    --raw-line 'pub const MAX_OSPATH: usize = 260;' \
    --raw-line '#[cfg(target_os = "macos")]' \
    --raw-line 'pub const MAX_OSPATH: usize = 1024;' \
    --raw-line '#[cfg(all(unix, not(target_os = "macos")))]' \
    --raw-line 'pub const MAX_OSPATH: usize = 4096;' \
    --raw-line '#[repr(C)]' \
    --raw-line 'pub struct steamgame_s {' \
    --raw-line '    pub appid: ::std::os::raw::c_int,' \
    --raw-line '    pub subdir: *mut ::std::os::raw::c_char,' \
    --raw-line '    pub library: [::std::os::raw::c_char; MAX_OSPATH],' \
    --raw-line '}' \
    --raw-line 'pub type steamgame_t = steamgame_s;' \
    --raw-line '#[repr(C)]' \
    --raw-line 'pub struct findfile_s {' \
    --raw-line '    pub attribs: fileattribs_t,' \
    --raw-line '    pub name: [::std::os::raw::c_char; MAX_OSPATH],' \
    --raw-line '}' \
    --raw-line 'pub type findfile_t = findfile_s;' \
    --raw-line '// com_gamedir is char[MAX_OSPATH]: declared by hand for the same' \
    --raw-line '// platform-dependent-array reason as the structs above.' \
    --raw-line 'extern "C" {' \
    --raw-line '    pub static mut com_gamedir: [::std::os::raw::c_char; MAX_OSPATH];' \
    --raw-line '}' \
    --allowlist-function 'Mem_Alloc|Mem_AllocNonZero|Mem_Realloc|Mem_Free' \
    --allowlist-function 'COM_LoadFile|COM_FOpenFile|COM_FOpenPrefFile|COM_CheckParm|COM_FileBase|COM_AddExtension' \
    --allowlist-function 'FS_fgets|FS_rewind|FS_fclose|FS_fread|FS_fseek|FS_feof|FS_ferror|Sys_ftell|Sys_filelength' \
    --allowlist-function 'Cvar_Set|Con_Printf|Con_Warning|Con_DPrintf|Con_DPrintf2|Sys_Error' \
    --allowlist-function 'COM_SeedRand|COM_Rand|COM_ThreadFileSize|COM_ThreadFileFromPak' \
    --allowlist-function 'COM_SetThreadFileSize|COM_SetThreadFileFromPak|COM_ThreadToken|COM_CheckParmNext' \
    --allowlist-function 'COM_HostBasedir|COM_HostUserdir|COM_SetHostUserdir|COM_Game_f|COM_CheckRegistered|COM_Parse' \
    --allowlist-function 'COM_LoadMallocFile_TextMode_OSPath|COM_CloseFile' \
    --allowlist-function 'Sys_FileOpenRead|Sys_FileOpenWrite|Sys_FileClose|Sys_FileSeek|Sys_FileRead|Sys_FileWrite' \
    --allowlist-function 'Sys_FileType|Sys_DuplicateHandle|Sys_MemFileOpenRead|Sys_mkdir|Sys_fopen|Sys_fseek' \
    --allowlist-function 'Sys_FindFirst|Sys_FindNext|Sys_FindClose|Sys_Printf|Sys_GetPrefPath' \
    --allowlist-function 'Sys_MessageBoxWarning|Sys_QuitNoShutdown|Sys_SelectFolder' \
    --allowlist-function 'Sys_GetSteamDir|Sys_GetGOGQuakeDir|Sys_GetGOGQuakeEnhancedDir|Sys_GetEGSManifestDir|Sys_GetEGSLauncherData|Sys_GetNightdiveUserDir' \
    --allowlist-function 'Steam_Init|ChooseQuakeFlavor|Cvar_RegisterVariable|Cmd_AddCommand2' \
    --allowlist-function 'COM_StripExtension|COM_SkipPath|q_strtrim' \
    --allowlist-function 'Image_DecodeSTBMem' \
    --allowlist-function 'QMutex_Create|QMutex_Destroy|QMutex_Lock|QMutex_Unlock' \
    --allowlist-function 'SNDDMA_Init|SNDDMA_GetDMAPos|SNDDMA_Shutdown|SNDDMA_LockBuffer|SNDDMA_Submit|SNDDMA_BlockSound|SNDDMA_UnblockSound' \
    --allowlist-function 'S_LoadSound|GetWavinfo|SND_InitScaletable|S_PaintChannels' \
    --allowlist-function 'Harness_SNDDMA_Init|Harness_SNDDMA_GetDMAPos|Harness_SNDDMA_Shutdown|Harness_SndPaint' \
    --allowlist-function 'Cvar_SetQuick|Cvar_SetValue|Cvar_SetCallback' \
    --allowlist-function 'Cmd_Argc|Cmd_Argv|Con_SafePrintf|COM_FileGetExtension|FS_filelength|COM_FileExists' \
    --allowlist-function 'SND_Glue_ClientConnected|SND_Glue_ViewEntity|SND_Glue_Worldmodel|SND_Glue_PointInLeaf|SND_Glue_PauseLoops' \
    --allowlist-var 'com_argc|com_argv' \
    --allowlist-var 'shm|snd_mutex|snd_channels|total_channels|soundtime|paintedtime|s_rawend|s_rawsamples' \
    --allowlist-var 'listener_origin|listener_forward|listener_right|listener_up' \
    --allowlist-var 'sndspeed|snd_mixspeed|snd_filterquality|sfxvolume|loadas8bit|bgmvolume|snd_waterfx|snd_pauselooping' \
    --allowlist-var 'precache' \
    --allowlist-var 'host_frametime|host_framecount|harness_sndhash|safemode|sn'\
    --allowlist-var 'flac_codec|mp3_codec|vorbis_codec|opus_codec' \
    --allowlist-var 'registered|cmdline|developer|multiuser|isDedicated|harness_active|external_ents' \
    --allowlist-var 'vkquake_pak|vkquake_pak_size|vkquake_pak_decompressed_size' \
    -o rust/quake-c-sys/src/generated.rs \
    -- -IQuake

echo "wrote rust/quake-c-sys/src/generated.rs"
