#!/bin/bash
# Regenerate the committed bindgen output in rust/quake-c-sys/src/generated.rs.
#
# ADR-011 (as amended in Phase 1): bindings are generated by this script and
# committed, rather than generated at build time, so libclang is not a build
# prerequisite; the rust.yml bindgen-smoke CI job reruns this script and fails
# on any diff, preserving the single-source-of-truth property.
#
# Layout tests are disabled: the committed output must be portable across the
# three CI OSes, and bindgen layout tests hardcode the generation host's type
# sizes. Struct layout drift is covered by the differential test suite in
# rust/quake-ctest and the signature-parity check.
set -euo pipefail
cd "$(dirname "$0")/.."

# FILE is blocklisted and re-declared opaque: bindgen would otherwise expand
# the generation host's libc struct (e.g. Darwin __sFILE), which is not
# portable; the engine only ever passes FILE* through.
bindgen rust/quake-c-sys/bindings_wrapper.h \
    --no-layout-tests \
    --no-doc-comments \
    --blocklist-type 'FILE|__sFILE.*|__sbuf|fpos_t|__darwin_.*|__int64_t|_IO_.*|_iobuf|__off_t|__off64_t' \
    --raw-line '// opaque stdio FILE: only ever passed through as a pointer' \
    --raw-line '#[repr(C)]' \
    --raw-line 'pub struct FILE {' \
    --raw-line '    _opaque: [u8; 0],' \
    --raw-line '}' \
    --allowlist-function 'Mem_Alloc|Mem_AllocNonZero|Mem_Realloc|Mem_Free' \
    --allowlist-function 'COM_LoadFile|COM_FOpenFile|COM_FOpenPrefFile|COM_CheckParm|COM_FileBase|COM_AddExtension' \
    --allowlist-function 'FS_fgets|FS_rewind|FS_fclose|FS_fread|FS_fseek|FS_feof|FS_ferror|Sys_ftell|Sys_filelength' \
    --allowlist-function 'Cvar_Set|Con_Printf|Con_Warning|Con_DPrintf|Con_DPrintf2|Sys_Error' \
    --allowlist-function 'COM_SeedRand|COM_Rand|COM_ThreadFileSize|COM_ThreadFileFromPak' \
    --allowlist-var 'com_argc|com_argv' \
    -o rust/quake-c-sys/src/generated.rs \
    -- -IQuake

echo "wrote rust/quake-c-sys/src/generated.rs"
