//! Compiles the original C implementations (renamed to c_ref_*) into the
//! differential test binaries. The C sources are compiled straight out of
//! Quake/ while they exist; the Phase 1 deletion step repoints this at frozen
//! copies under csrc/.

use std::path::PathBuf;

const C_SOURCES: &[&str] = &[
    "Quake/cfgfile.c",
    "Quake/common_fs.c",
    "Quake/crc.c",
    "Quake/hash_map.c",
    "Quake/image_decode.c",
    "Quake/image_stb.c",
    "Quake/json.c",
    "Quake/mathlib.c",
    "Quake/mdfour.c",
    "Quake/model_parse.c",
    "Quake/net_dgrm_rel.c",
    "Quake/net_loop.c",
    "Quake/net_msg.c",
    "Quake/snd_mem.c",
    "Quake/snd_codec.c",
    "Quake/snd_dma.c",
    "Quake/snd_mix.c",
    "Quake/snd_mp3tag.c",
    "Quake/snd_umx.c",
    "Quake/snd_wave.c",
    "Quake/steam.c",
    "Quake/strlcpy.c",
    "Quake/strlcat.c",
    "Quake/wad.c",
];

/// Builds the synthetic embedded vkquake.pak: a tiny valid single-entry pak,
/// raw-deflate compressed exactly like Meson's generated embedded_pak.c (the
/// real one is generated at build time and is not in git). The c_ref side
/// inflates it with the vendored tinfl, the Rust side with miniz_oxide, so
/// mounting it differentially tests the inflate path too.
fn generate_embedded_pak(out_dir: &std::path::Path) -> PathBuf {
    let payload = b"embedded vkquake.pak content marker\n";
    let name = b"embedded/marker.txt";

    let mut pak: Vec<u8> = Vec::new();
    pak.extend_from_slice(b"PACK");
    let dirofs = 12 + payload.len() as i32;
    pak.extend_from_slice(&dirofs.to_le_bytes());
    pak.extend_from_slice(&64i32.to_le_bytes()); // dirlen: one entry
    pak.extend_from_slice(payload);
    let mut entry_name = [0u8; 56];
    entry_name[..name.len()].copy_from_slice(name);
    pak.extend_from_slice(&entry_name);
    pak.extend_from_slice(&12i32.to_le_bytes()); // filepos
    pak.extend_from_slice(&(payload.len() as i32).to_le_bytes()); // filelen

    let compressed = miniz_oxide::deflate::compress_to_vec(&pak, 9);

    let mut src = String::new();
    src.push_str("/* generated by quake-ctest build.rs: synthetic embedded pak */\n");
    src.push_str("const unsigned char vkquake_pak[] = {");
    for (i, b) in compressed.iter().enumerate() {
        if i % 16 == 0 {
            src.push('\n');
        }
        src.push_str(&format!("{},", b));
    }
    src.push_str("\n};\n");
    src.push_str(&format!(
        "const int vkquake_pak_size = {};\n",
        compressed.len()
    ));
    src.push_str(&format!(
        "const int vkquake_pak_decompressed_size = {};\n",
        pak.len()
    ));

    let path = out_dir.join("embedded_pak.c");
    std::fs::write(&path, src).unwrap();
    path
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let repo_root = manifest.ancestors().nth(2).unwrap().to_path_buf();
    let prelude = manifest.join("include").join("c_ref_prelude.h");

    let mut build = cc::Build::new();
    build
        .include(manifest.join("include"))
        .include(repo_root.join("Quake"))
        // ADR-010: the engine pins -ffp-contract=off (meson.build) so C and
        // Rust agree on FMA behavior; the reference build must match. The
        // no-builtin flags stop clang fusing adjacent sinf/cosf into Apple's
        // __sincosf_stret, whose results differ from separate calls by 1 ulp
        // (renderer-only divergence, accepted in ADR-010's Phase 1 amendment).
        .flag_if_supported("-ffp-contract=off")
        .flag_if_supported("-fno-builtin-sinf")
        .flag_if_supported("-fno-builtin-cosf");

    // the engine compiles as gnu11 (meson c_std / common.make); MSVC cl.exe
    // defaults to a C89-ish mode where the headers' C11 `bool` fails, so pin
    // the standard explicitly (c11 is the closest cl.exe offers)
    if build.get_compiler().is_like_msvc() {
        build.flag("/std:c11");
        build.flag(format!("/FI{}", prelude.display()));
    } else {
        build.flag("-std=gnu11");
        build.flag("-include").flag(prelude.to_str().unwrap());
    }

    for src in C_SOURCES {
        let path = repo_root.join(src);
        println!("cargo:rerun-if-changed={}", path.display());
        build.file(path);
    }
    // Phase 5 M7b: the unix UDP landriver oracle (net_wins.c stays C-only
    // and untested here; see the task plan's ADR-017 deferral note)
    if std::env::var_os("CARGO_CFG_UNIX").is_some() {
        let path = repo_root.join("Quake/net_udp.c");
        println!("cargo:rerun-if-changed={}", path.display());
        build.file(path);
    }
    // common_fs.c compiles miniz.c inside its own TU (stb-style include);
    // image_stb.c does the same with stb_image.h
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("Quake/miniz.c").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("Quake/stb_image.h").display()
    );
    for stub in [
        "snprintf_oracle.c",
        "stubs.c",
        "abi_probe.c",
        "anorms_ref.c",
        "hashers_ref.c",
        "qctype_ref.c",
    ] {
        let path = manifest.join("stubs").join(stub);
        println!("cargo:rerun-if-changed={}", path.display());
        build.file(path);
    }
    build.file(generate_embedded_pak(&out_dir));
    println!("cargo:rerun-if-changed={}", prelude.display());

    build.compile("quake_c_ref");
}
