name: Windows CI (meson)

on: [push, pull_request]

jobs:
  build-windows-meson:
    name: Build Windows (meson)
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
    steps:
    - uses: actions/checkout@v6
    - name: Determine version
      id: version
      run: |
        if ($env:GITHUB_REF -like 'refs/tags/*') {
          $version = $env:GITHUB_REF_NAME
        } else {
          $version = $env:GITHUB_SHA.Substring(0, 8)
        }
        "version=$version" >> $env:GITHUB_OUTPUT
    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.6.0
      with:
        vulkan_version: 1.4.341.1
        install_runtime: false
        cache: true
        stripdown: true
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Install meson
      run: pip install meson ninja
    - name: Configure
      run: |
        $env:CC = 'clang-cl'
        meson setup builddir --buildtype=${{ matrix.buildtype }} -Ddebug=true -Dstrip=false -Duse_sdl3=enabled
    - name: Build
      run: meson compile -C builddir
    - name: Upload vkQuake
      uses: actions/upload-artifact@v7
      with:
        name: vkQuake meson (${{ matrix.buildtype }}, x64)
        path: |
            builddir/vkquake.exe
            builddir/*.dll
            builddir/*.pdb
    - name: Package
      if: matrix.buildtype == 'release'
      run: |
        $version = '${{ steps.version.outputs.version }}'
        $srcdir = 'builddir'
        $compress = @{
          Path = "$srcdir\*.exe", "$srcdir\vkquake.pdb", "$srcdir\*.dll", 'LICENSE.txt'
          CompressionLevel = 'Optimal'
          DestinationPath = "Packaging\Windows\vkQuake-${version}_windows_x64.zip"
        }
        Compress-Archive @compress
        choco install nsis -y --no-progress
        Set-Location Packaging\Windows
        & "${env:ProgramFiles(x86)}\NSIS\makensis.exe" -V4 '-DSRCDIR=..\..\builddir' '-DPLATFORM=windows_x64' "-DVERSION=$version" vkQuake.nsi
        if (-not $?) { throw "makensis failed" }
    - name: Upload package
      if: matrix.buildtype == 'release'
      uses: actions/upload-artifact@v7
      with:
        name: vkQuake package (x64)
        path: |
            Packaging\Windows\vkQuake-*.zip
            Packaging\Windows\vkQuake-Installer-*.exe
    - name: Attach to release
      if: matrix.buildtype == 'release' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: |
          Packaging/Windows/vkQuake-*.zip
          Packaging/Windows/vkQuake-Installer-*.exe
